from cla_utils.exercises1 import *
from cla_utils.exercises2 import *
from cla_utils.exercises3 import *
from cla_utils.exercises4 import *
from cla_utils.exercises5 import *
from cla_utils.exercises6 import *
from cla_utils.exercises7 import *
from cla_utils.exercises8 import *
from cla_utils.exercises9 import *
from cla_utils.exercises10 import *
from numpy.linalg import norm
