#! /usr/bin/env bash
if [[ $VIRTUAL_ENV ]];
then
    pip install sphinx sphinxcontrib-bibtex sphinxcontrib-proof
    pip install git+https://github.com/sphinx-contrib/youtube.git
else
    echo ERROR: please activate the computational linear algebra course venv
    exit 1
fi
